---
debug: true
log:
  level: debug
  format: json
  output_to_file: execution.log
  output_to_stdout: true
telemetry:
  enabled: true
  traces:
#    endpoint: "otlp:4317"
    endpoint: "otlp:4317"
  metrics:
#    endpoint: "otlp:4317"
    endpoint: "otlp:4317"
