log:
  level: debug
  format: json
  output_to_file: execution.log
  output_to_stdout: true
telemetry:
  enabled: true
  traces:
    endpoint: "localhost:4317"
  metrics:
    endpoint: "localhost:4317"
  logs:
    endpoint: "localhost:4317"
